name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions with Docker container 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    container: node:20
    steps:
      - run: node --version
      - run: npm --version

